name: CI Checks

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Formatting
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Linting - ruff
        uses: astral-sh/ruff-action@v1
      - name: Check Linting - pylint
        uses: davidslusser/actions_python_pylint@v1.0.0
        with:
          src: "solutions tests"
          options: '|| echo "::warning title=\"Pylint Error(s)\"::Discuss solutions in code review."'
        if: always()

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: python -m unittest
