name: CI Checks

on: [push, pull_request, workflow_dispatch]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Formatting
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"

  linting_py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Python Linting
        uses: colevandersWands/et6_linting_dev@main
        with:
          src: "solutions tests"

  linting_md:
    runs-on: ubuntu-latest
    steps:
        - name: Check Markdown Linting
          uses: avto-dev/markdown-lint@v1
          with:
            args: './'
      # - name: Check Markdown Linting
      #   uses: nosborn/github-action-markdown-cli@v3.3.0
      #   with:
      #     files: "."
      #   continue-on-error: true
          
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python version
        run: python --version
        shell: bash
      - name: Run Tests
        run: python -m unittest
        shell: bash
