name: CI Checks

on: [push, pull_request, workflow_dispatch]

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Run Code Quality Checks
        uses: colevandersWands/et6_ci_checks_dev@v0
        with:
          src: "solutions tests"
              
