# This workflow will install Python dependencies, run tests, check formatting and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PR Checks

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Check Formatting
        uses: astral-sh/ruff-action@v1
        with:
            args: "format --check"
      
      - name: Check Linting
        uses: astral-sh/ruff-action@v1
      
      - name: Run Tests
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        run: python -m unittest
  