# This workflow will install Python dependencies, run tests, check formatting and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PR Checks

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:  "3.12"
        include:
          - python-version: "3.12"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - run: pip install -r requirements.txt

      - name: Check Formatting
        run: ruff format --check
      
      - name: Check Linting
        run: ruff check
      
      - name: Run Tests
        run: python -m unittest
  