name: PR Checks

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Formatting
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Linting
        uses: astral-sh/ruff-action@v1

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: python -m unittest
