# This workflow will install Python dependencies, run tests, check formatting and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PR Checks

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        include:
          - python-version: "3.11"
            use_pandas: 1
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - run: poetry install

      - name: Check Formatting
        run: poetry run ruff format --check
      
      - name: Check Linting
        run: poetry run ruff check
      
      - name: Run Tests
        run: python -m unittest
  